// <auto-generated />
using System;
using IventarioDeRecursos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IventarioDeRecursos.Migrations
{
    [DbContext(typeof(RecursoContext))]
    [Migration("20210920221247_recursodb4")]
    partial class recursodb4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IventarioDeRecursos.Models.Movimentacao", b =>
                {
                    b.Property<int>("MovimentacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEntradaRecurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeSaidaRecurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecursoDescricao")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MovimentacaoID");

                    b.HasIndex("RecursoDescricao");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("IventarioDeRecursos.Models.Recurso", b =>
                {
                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Descricao");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("IventarioDeRecursos.Models.Movimentacao", b =>
                {
                    b.HasOne("IventarioDeRecursos.Models.Recurso", "Recurso")
                        .WithMany("Movimento")
                        .HasForeignKey("RecursoDescricao");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("IventarioDeRecursos.Models.Recurso", b =>
                {
                    b.Navigation("Movimento");
                });
#pragma warning restore 612, 618
        }
    }
}
